version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 736745
      POSTGRES_DB: ServicoBancario-main
    ports:
      - "5432:5432"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile-spring
    ports:
      - "9007:9007"
    depends_on:
      - postgres
